### ISSUE TITLE
Create a readme file for this website

### ISSUE THREAD

**Issue by raunakkumarsingh** [raunakkumarsingh/DSA-Sheet#3]
Create a readme file for this website [dsasheet.vercel.app/](https://dsasheet.vercel.app/)

**Comment by najeebkp** [comment]
Hi @raunakkumarsingh  please assign me this task. and give me data which should be shown in readme file

**Comment by raunakkumarsingh** [comment]
1) 1-2 full size image 
2) write a brief description about website
3)provide techStack in inovative way -React,Node,MongoDB,JavaScript,CSS,Bootstrap
4)whatever you can do yourself to provide it a better look😊

**Comment by raunakkumarsingh** [comment]
1) 1-2 full size image
2) write a brief description about website
3) provide techStack in inovative way -React,Node,MongoDB,JavaScript,CSS,Bootstrap
4) whatever you can do yourself to provide it a better look😊

**Comment by raunakkumarsingh** [comment]
Thanks For creating This  I Really appreciate your work.
